CREATE TABLE ORDERS (
    ID              BIGSERIAL PRIMARY KEY,
    ORDER_CODE      VARCHAR(50) NOT NULL UNIQUE,
    CUSTOMER_NAME   VARCHAR(255) NOT NULL,
    AMOUNT          NUMERIC(18, 2) NOT NULL,
    STATUS          VARCHAR(30) NOT NULL,
    CREATED_AT      TIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP NOT NULL
);