CREATE TABLE OUTBOUND_SEND_QUEUE (
    ID                    BIGSERIAL PRIMARY KEY,
    REQUEST_ID            VARCHAR(36) NOT NULL UNIQUE,
    BUSINESS_TYPE         VARCHAR(50) NOT NULL,
    BUSINESS_ID           BIGINT NOT NULL,
    BUSINESS_CODE         VARCHAR(100),
    ACTION                VARCHAR(100) NOT NULL,
    REQUEST_TOPIC         VARCHAR(255) NOT NULL,
    RESULT_TOPIC          VARCHAR(255) NOT NULL,
    PAYLOAD               TEXT NOT NULL,
    STATUS                VARCHAR(30) NOT NULL,
    RETRY_COUNT           INTEGER NOT NULL DEFAULT 0,
    NEXT_RETRY_AT         TIMESTAMP,
    PROVIDER_MESSAGE_ID   VARCHAR(255),
    ERROR_CODE            VARCHAR(100),
    ERROR_MESSAGE         VARCHAR(2000),
    CREATED_AT            TIMESTAMP NOT NULL,
    UPDATED_AT            TIMESTAMP NOT NULL
);

CREATE INDEX IDX_OUTBOUND_QUEUE_READY
    ON OUTBOUND_SEND_QUEUE (STATUS, NEXT_RETRY_AT);