CREATE TABLE PROCESSED_MESSAGE (
    ID              BIGSERIAL PRIMARY KEY,
    MESSAGE_ID      VARCHAR(100) NOT NULL,
    CONSUMER_NAME   VARCHAR(100) NOT NULL,
    PROCESSED_AT    TIMESTAMP NOT NULL,
    CONSTRAINT UK_PROCESSED_MESSAGE
        UNIQUE (MESSAGE_ID, CONSUMER_NAME)
);
